ConductorOne/baton-sdk

pkg/us3/s3.go
It is helpful for the caller to know which bucket the client is configured for.
=> Add Bucket() to us3.S3Client

.github/workflows/ci.yaml, .github/workflows/main.yaml, internal/dotc1z/dotc1z.go, internal/dotc1z/sync_runs.go, pkg/connectorstore/connectorstore.go, pkg/sync/syncer.go
In order to prevent c1z files from growing unbounded, this change will perform automatic cleanup on the contents of the local db after a sync.
By default it will keep the last sync performed, and the previous sync if available. This allows diffing to continue to work without storing all of the data.
In order to disable the automatic cleanup, the user can set `BATON_SKIP_CLEANUP=1` in the environment, and cleanup will not happen. Users can also set `BATON_KEEP_SYNC_COUNT=5` in order to increase the number of syncs from the default 2. Sync count is clamped to 1 as a minimum.
=> Automatically cleanup old sync data in the c1z after a sync

pkg/sync/progress.go, pkg/sync/syncer.go
Add an optional callback to the syncer that reports progress while running the current sync.
Currently it reports the current action, resource (if available), and count of objects processed. The work is not done in this PR, but this could be reasonably combined with the `Stats()` capability of a c1z to fetch object counts from the previous sync and be able estimate sync progress.
Additionally, if the sync context is cancelled with cause, return that error.
=> Add an optional callback to the syncer that reports progress.

pkg/sync/progress.go, pkg/sync/state.go, pkg/sync/syncer.go
Before this change, we would sync all resources(and their children types) of a given resource type in a single sync run without checkpointing. This means that if the sync failed in the middle of syncing some resource type, the sync would have to begin again at the first page of resources for that type.
After this change, the syncer will checkpoint after each page of resources processed so that we can resume without having to repeat a large amount of work.
This is accomplished by refactoring how resources are synced. Now we will push individual state actions onto the sync stack as we discover pages and child resource types.
Previously we kept a slice of the resources we've seen so that we wouldn't find ourselves in an infinite loop of syncing resources. Because we are calling …
=> Checkpoint more often while syncing resources and their children types

pkg/dotc1z/decoder.go, pkg/dotc1z/file.go, pkg/us3/s3.go
* Let the aws SDK calculate sha256 checksums on upload for better multipart support
* Add support for configuring decoder limits via the environment.
`BATON_DECODER_MAX_DECODED_SIZE_MB` can be set to limit the maximum size of a decoded/uncompressed c1z in megabytes. This currently defaults to 1GB.
`BATON_DECODER_MAX_MEMORY_MB` can be set to limit the maximum amount of memory to use while decoding a c1z. This currently defaults to 32MB.
=> Large file upload support

internal/connector/connector.go, pkg/cli/cli.go, pkg/cli/config.go, pkg/connectorrunner/runner.go, pkg/connectorrunner/tasks/naive.go, pkg/connectorrunner/tasks/tasks.go, pkg/sync/syncer.go
The goal of this change is to refactor the CLI harness to take ownership of the process and introduce the idea of a 'daemon' mode for connectors. The SDK takes over the main run loop of the connector, working off of a serial work queue. Today this includes a single task type for Syncs, but you can imagine adding `Grant` and `Revoke` tasks as well. 
This is the first step on the path to allowing connectors to run in "service mode" where they will communicate with an upstream API in order to get work to do and submit the results of each task.
This is a breaking change for connectors consuming the SDK. They will be required to make updates to begin using this version of the SDK. 
The primary change here is that the SDK cli package takes control of running the connector implementation instead …
=> Daemon Refactoring

pkg/dotc1z/c1file.go, pkg/dotc1z/c1file_test.go, pkg/dotc1z/file.go
Unconditionally remove the temp dir backing the C1File implementation on Close().
This avoids orphaning a tempdir if you open a C1File but make no changes that need written back out.
Also other small cleanup.
=> Unconditionally remove the temp dir backing the C1File implementation on Close().

pkg/dotc1z/decoder.go, pkg/dotc1z/file.go, pkg/dotc1z/manager/local/local.go, pkg/dotc1z/manager/manager.go, pkg/dotc1z/manager/s3/s3.go
Check the environment later on to ensure it always happens.
I also realized that the `LoadRaw()` method on the c1z manager was loading the entire file into memory instead of serving it from disk.
=> Refactor c1z decoder options

pkg/cli/cli.go, pkg/cli/config.go, pkg/cli/service_windows.go
- Drop `--daemonize` flag. It wasn't truly being used. We know we need to run in daemon mode if a client id is provided to us *or* we detect we're running as a service.
- Make `--provisioning` not hidden now that the upstream service is available.
=> Clean up cli flags related to service mode

pkg/sync/syncer.go
This prevents logs like the following from showing multiple times:
```
{"level":"info","ts":1695804491.206762,"caller":"sync/syncer.go:786","msg":"Syncing grants..."}
{"level":"info","ts":1695804520.664175,"caller":"sync/syncer.go:786","msg":"Syncing grants..."}
{"level":"info","ts":1695804552.543251,"caller":"sync/syncer.go:786","msg":"Syncing grants..."}
```
=> Only log the sync step on the first page of results.

pkg/dotc1z/sync_runs.go
Vacuum after removing old generations of data.
Without this vacuuming, the c1z database will continue to grow in size even though we are removing old data. Vacuuming allows us to reclaim the space used by previous generations, keeping the decompressed file size as small as expected.
=> Add new method for vacuuming a c1z db.

pkg/cli/cli.go, pkg/cli/service_unix.go
This fixes a bug that happens when testing baton cli tools in CI (where stdin isn't a tty).
Needed so that CI passes on https://github.com/ConductorOne/baton-ldap/pull/10
=> Only append client credentials if they exist, not if stdin isn't a tty.

pkg/helpers/helpers.go, pkg/helpers/helpers_test.go
There are some helper functions in various baton connectors. We should probably put the common ones in baton-sdk. At least that way our connectors will have the same bugs instead of different bugs. :)
=> Add a helper pkg.

pkg/cli/cli.go, pkg/connectorbuilder/connectorbuilder.go
Before:
```json
{"resourceTypeCapabilities":[{"resourceType":{"id":"role", "displayName":"Role", "traits":["TRAIT_ROLE"], "description":"A role in Snipe-IT"}, "capabilities":["CAPABILITY_SYNC"]}, {"resourceType":{"id":"user", "displayName":"User", "traits":["TRAIT_USER"], "annotations":[{"@type":"type.googleapis.com/c1.connector.v2.SkipEntitlementsAndGrants"}], "description":"A user in Snipe-IT"}, "capabilities":["CAPABILITY_SYNC"]}, {"resourceType":{"id":"group", "displayName":"Group", "traits":["TRAIT_GROUP"], "description":"A group in Snipe-IT"}, "capabilities":["CAPABILITY_SYNC", "CAPABILITY_PROVISION"]}]}
```
After: 
```json
{
"@type":  "type.googleapis.com/c1.connector.v2.ConnectorCapabilities",
"resourceTypeCapabilities":  [
{
"resourceType":  {
"id":  "user",
"displayName": …
```
=> Sort capabilities and pretty print them.

pkg/sync/syncer.go
If there is an error and it is explicitly a sql not found error, we should create the principal, otherwise return the error.
=> Fix typo causing incorrect error handling when ensuring a grant principal exists

pkg/httpclient/httpclient.go, pkg/uhttp/wrapper.go, pkg/uhttp/wrapper_test.go
=> feat: httpclient with base functions

pkg/connectorbuilder/connectorbuilder.go
If this ever happens, the connector will be stuck in an infinite loop, fetching the same page over and over.
=> Error if connector returns same pagination as previous list call.

pkg/dotc1z/decoder.go
We don't initialize underlying decoder until we call `Read()` the first time, so don't try to close a nil decoder if we never `Read()` from one.
=> Tiny: We don't need to Close() the underlying reader if we never initialized it by calling Read().

pkg/uhttp/wrapper.go, pkg/uhttp/wrapper_test.go
It'd be nice to not have to deal with this after every call to do request.
=> Close response body.

pkg/uhttp/authcredentials.go
I need to apply changes to `Transport` layer so I would like to expose options of `NewClient` to `GetClient`.
=> feat: expose NewClient options to credentials wrappers

pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, pkg/uhttp/wrapper.go, pkg/uhttp/wrapper_test.go
- Check content type of JSON and XML responses before trying to parse the body.
- Add HTTP status 429 handling to helpers.ExtractRateLimitData().
=> HTTP helper improvements

pkg/helpers/helpers.go, pkg/sync/syncer.go, pkg/uhttp/wrapper.go, pkg/uhttp/wrapper_test.go
This changes the http client and the syncer so that individual connectors don't have to handle every recoverable http error. If the error status is something we can retry or recover from, we do so. For example, 429 (too many requests) caused connectors to error out. This PR fixes that.
TODO:
If this works, we can simplify connector code and avoid an entire class of bugs.
=> General retry logic in syncing

pkg/provisioner/provisioner.go
This makes the CLI behavior the same as grant/revoke in service mode, which should force us to fix any connectors that rely on parent resources in grant/revoke. (eg: Slack)
=> Omit parent resource IDs in grant/revoke.

pkg/sync/expand.go, pkg/sync/expand_test.go, pkg/sync/syncer.go
- Remove getDescendants() and just get node ids directly. This should drastically speed up GetCycles().
- Give up fixing cycles after 10 tries.
- Don't call GetCycles() after fixing cycles.
=> Performance improvements

pkg/cli/cli.go
`--ticketing` flag enables ticketing support while running in service mode.
Also adjusts logic a bit to make sure we can support provisioning and ticketing at the same time.
=> Add ticketing flag

pkg/logging/logging.go
This fixes the exponential notation of timestamps and shows human readable ones. Also it capitalizes the log level and a few other things.
Before:
After:
=> Use opinionated developer encoder config for console logging.

pkg/dotc1z/entitlements.go, pkg/dotc1z/grants.go, pkg/dotc1z/resouce_types.go, pkg/dotc1z/resources.go
Previously, if you tried to run a provision command with a bad grant/resource/whatever ID, you'd see an error like this:
```
{
"level": "error",
"ts": 1717434766.783422,
"caller": "cli/cli.go:173",
"msg": "error running connector",
"error": "runner: error processing task: sql: no rows in result set"
}
```
Now it says what went wrong:
```
{
"level": "error",
"ts": 1717436325.934488,
"caller": "cli/cli.go:173",
"msg": "error running connector",
"error": "runner: error processing task: error fetching grant 'group:cn=testgroup00001,dc=example,dc=org:member:user:cn=testuser00000,dc=example,dc=org': sql: no rows in result set"
}
```
=> Add some better error messages and logs to c1z functions.

pkg/helpers/helpers.go
Content type headers can have a charset, so check the prefix instead of directly comparing.
=> Fix IsXMLContentType

pkg/dotc1z/assets.go, pkg/dotc1z/entitlements.go, pkg/dotc1z/grants.go, pkg/dotc1z/resouce_types.go, pkg/dotc1z/resources.go
These logs produce a lot of noise while using the debug log level. The are useful for tracing execution, but there are better methods for using that. 
This PR removes these logs, as they are more suited for a TRACE log level that is unavailable to us.
=> Drop dotc1z debug logs

pkg/tasks/c1api/create_ticket.go, pkg/tasks/c1api/get_ticket.go, pkg/tasks/c1api/list_ticket_schemas.go
- We need the external ticket annotation to record retry attempts 
- Makes create ticket failure retryable
=> Return annotations for failed ticket tasks 

go.sum, pkg/connectorstore/connectorstore.go, pkg/dotc1z/c1file.go, pkg/dotc1z/c1file_test.go, pkg/dotc1z/entitlements.go, pkg/dotc1z/grants.go, pkg/dotc1z/resouce_types.go, pkg/dotc1z/resources.go, pkg/dotc1z/sql_helpers.go, pkg/sync/syncer.go, pkg/sync/syncer_test.go, vendor/github.com/doug-martin/goqu/v9/dialect/sqlite3/sqlite3.go, vendor/modules.txt
- Adds a basic full Sync() benchmark.
- Based on early profiling of this, add a Multi-Write / Bulk `PutGrants()` function as an interface upgrade to Writer.  Just this change has a ~67.33% reduction in sync time for the basic benchmark.
- Also fix an issue with `goqu` Dialect;  We were trying to use `goqu.Dialect("sqlite3")`.  But if this Dialect isn't loaded, goqu makes a duplicate of the default... which is a huge memory allocation.  So... by using an underscore import of the dialect module, we cut memory allocations by ~16%.
```
goos: linux
goarch: amd64
pkg: github.com/conductorone/baton-sdk/pkg/sync
cpu: Intel(R) Xeon(R) E-2274G CPU @ 4.00GHz
│   old.text   │              new.text               │
│    sec/op    │   sec/op     vs base                │
ExpandCircle-8   1644.0m ± 1% …
```
=> [Performance]: Basic Benchmark & Multi-Put objects

pkg/uhttp/wrapper.go, pkg/uhttp/wrapper_test.go
A common pattern in connectors is to create a helper function like `makeRequest()` that calls `client.wrapper.Do()`. When dealing with a JSON API, most of the client methods expect a response body. However, some APIs respond with an empty body when they `204`. To handle this we have to do something a little janky: 
```go
doOptions := []uhttp.DoOption{
WithConfluenceRatelimitData(&ratelimitData),
}
if target != nil {
doOptions = append(doOptions, uhttp.WithJSONResponse(target))
}
response, err := c.wrapper.Do(request, doOptions...)
```
I want to change `WithJSONResponse()` to take `nil` to mean that we expect the body to be empty and that there is no JSON.
I think it's also totally reasonable to not do this and just make sure not to call `WithJSONResponse()` when we're expecting a `204`.
=> feat: Allow `WithJSONResponse()` and `WithXMLResponse()` to work with empty response bodies

pkg/tasks/local/ticket.go, pkg/types/ticket/custom_fields.go
- We don't require status but if the schema didn't include status we were still erroring 
- Change ticket type to not be required since not all ticket systems require type
=> Don't require ticket status and type

pkg/config/config.go
This fix a panic when calling `cli.MakeMainCommand`. We also receive a list of `connectorrunner.Option` that's used in `cli.MakeMainCommand`
=> Pass getconnector and receive a list of connectorrunner.Option

pkg/sync/expand/graph_test.go
The entitlement graphs test suite is still flaky.
This PR makes the "two cycles" test ignore the order of the expected cycles.
=> fix: Assert that the cycle is one of the options

pkg/config/config.go, pkg/field/relationships.go, pkg/field/validation.go
- add constrain check to require at least one field/environment variable from a set
- add missing check for zero-value of string slice (missed in #176)
=> Add missing relationship constraint

pkg/sync/syncer.go
This changes the 1 second retry to a backoff. I tested it with baton-litmos.
=> Backoff retries.

pkg/config/config.go
Prevents conflicts with Cobra for not using any required flag when invoking a connector
- https://github.com/spf13/viper/issues/397
=> Set flags if their envvar counterparts are set

pkg/field/default_relationships.go
Remove client id/file mutually exclusive relationship
Because of the default value set for file, setting client-id gives the error `fields marked as mutually exclusive were set: file, client-id`
=> Remove client id/file mutually exclusive relationship

pkg/sdk/version.go, pkg/uhttp/transport.go
Fixes an issue where reusing it too many times would result in a ridiculously long user agent.
Also update the sdk version to be closer to accurate.
=> Don't rebuild user agent on every reuse of a roundtripper.

pkg/pagination/pagination.go
Omit empty fields when unmarshaling PageState. Use shorter names for fields.
This should help with very large page states that exceed the 4096 character limit.
=> Make PageState more compact

.github/workflows/update-hardcoded-version.yaml, Makefile, pkg/sdk/version.go
Looks like echo doesn't have a -e flag on some platforms.
=> Fix release version action.

pkg/uhttp/wrapper.go
This change allows you to specify a new `WithRateLimiter(num, period)` option when creating a new base http client.
`num`: the number of requests to be made during `period`
`period`: the duration to enforce the rate limit over
`WithRateLimiter(10, time*Minute)`: This would enforce a rate limit of 10 http requests per minute.
=> Add wrapper options to base http client, and add rate limiter option

pkg/sync/syncer.go
On my laptop, this logs about once every 10 seconds.
```
{"level":"info","ts":1734487902.506569,"caller":"sync/syncer.go:859","msg":"Expanding grants..."}
{"level":"info","ts":1734487902.74467,"caller":"sync/syncer.go:875","msg":"Finished loading entitlement graph","edges":6582}
{"level":"info","ts":1734487902.811059,"caller":"sync/syncer.go:1433","msg":"Expanding grants","depth":0,"actions":0}
{"level":"info","ts":1734487902.956737,"caller":"sync/syncer.go:1433","msg":"Expanding grants","depth":1,"actions":10000}
{"level":"info","ts":1734487906.959425,"caller":"sync/syncer.go:1433","msg":"Expanding grants","depth":1,"actions":9750}
...
```
=> Log grant expansion progress.

pkg/dotc1z/clone_sync.go
If other steps in CloneSync failed, we didn't clean up the temp dir.
=> Always clean up temp dir in CloneSync.
